apiVersion: v1
kind: Service
metadata:
  name: zenwebapi18-service
  labels:
    app: zenwebapi18
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: zenwebapi18
